# Generated by Django 3.0.6 on 2020-05-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='diplay_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
