# Generated by Django 3.0.6 on 2020-05-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_auto_20200518_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='Age',
            field=models.IntegerField(default=0),
        ),
    ]
