# Generated by Django 3.0.6 on 2020-05-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_myuser_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='diplay_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_name',
        ),
        migrations.AddField(
            model_name='myuser',
            name='displayname',
            field=models.CharField(default='testing', max_length=60),
        ),
    ]
